// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Data;

namespace WebBanHang.Migrations
{
    [DbContext(typeof(MvcBanHangContext))]
    [Migration("20201023071648_SanPham")]
    partial class SanPham
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("anhminhhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("giatien")
                        .HasColumnType("int");

                    b.Property<string>("maloaisp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluongtonkho")
                        .HasColumnType("int");

                    b.Property<string>("tensp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thongtin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
