// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Data;

namespace WebBanHang.Migrations
{
    [DbContext(typeof(MvcBanHangContext))]
    partial class MvcBanHangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.CTHoaDon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoaDonid")
                        .HasColumnType("int");

                    b.Property<int>("dongia")
                        .HasColumnType("int");

                    b.Property<string>("mahd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("masp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("HoaDonid");

                    b.ToTable("CTHoaDon");
                });

            modelBuilder.Entity("WebBanHang.Models.GioHang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TaiKhoanid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("masp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluong")
                        .HasColumnType("int");

                    b.Property<string>("tentaikhoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TaiKhoanid");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("WebBanHang.Models.HoaDon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TaiKhoanid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("diachigiaohang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaymua")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdtgiaohang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tentaikhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tongtien")
                        .HasColumnType("int");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("TaiKhoanid");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("WebBanHang.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tenloaisp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CTHoaDonid")
                        .HasColumnType("int");

                    b.Property<int?>("GioHangid")
                        .HasColumnType("int");

                    b.Property<string>("LoaiSanPhamid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("anhminhhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("giatien")
                        .HasColumnType("int");

                    b.Property<string>("maloaisp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluongtonkho")
                        .HasColumnType("int");

                    b.Property<string>("tensp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thongtin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CTHoaDonid");

                    b.HasIndex("GioHangid");

                    b.HasIndex("LoaiSanPhamid");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebBanHang.Models.TaiKhoan", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("diachi")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("laAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("WebBanHang.Models.CTHoaDon", b =>
                {
                    b.HasOne("WebBanHang.Models.HoaDon", "HoaDon")
                        .WithMany("CTHoaDon")
                        .HasForeignKey("HoaDonid");
                });

            modelBuilder.Entity("WebBanHang.Models.GioHang", b =>
                {
                    b.HasOne("WebBanHang.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanid");
                });

            modelBuilder.Entity("WebBanHang.Models.HoaDon", b =>
                {
                    b.HasOne("WebBanHang.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("HoaDons")
                        .HasForeignKey("TaiKhoanid");
                });

            modelBuilder.Entity("WebBanHang.Models.SanPham", b =>
                {
                    b.HasOne("WebBanHang.Models.CTHoaDon", "CTHoaDon")
                        .WithMany("SanPhams")
                        .HasForeignKey("CTHoaDonid");

                    b.HasOne("WebBanHang.Models.GioHang", null)
                        .WithMany("SanPhams")
                        .HasForeignKey("GioHangid");

                    b.HasOne("WebBanHang.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamid");
                });
#pragma warning restore 612, 618
        }
    }
}
